matches:
  - trigger: ':n1'
    replace: "Sandeep Reddy Battula"
  - trigger: ':a1'
    replace: "32"
  - trigger: ':c1'
    replace: "345739904878"  
  - trigger: ':na1'
    replace: "Sandeep Reddy Battula\t32"